# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bcba2ab928738e9718118115799891eb0084d9a5b811cb10a3cb3cfff098751551fca79d7688a8bfedb7e89465d49486f0b05af4acf46cf1899934cd48913459

test:
  secret_key_base: e20f4c9ed23ebf6d2543e0f702669a8fc12b010df187ddcb425de3010939a5b3fb71b8f8b1e3c14b930390e29baa5f4b5887b283e8085e5a78090023c7f3b7cb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
